server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/log/containers/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^_]+_){2})(?P<pod_name>[^_]+)_(?P<namespace>[^_]+)_(?P<uuid>.+)\.log
          source: filename
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
          pod_name:
          namespace:
      - output:
          source: output

  # Scrape mobile banking backend application logs
  - job_name: mobile-banking-backend
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
        replacement: "${1}"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "logstream"
      - source_labels: ["__meta_docker_container_label_logging_jobname"]
        target_label: "job"
    pipeline_stages:
      - json:
          expressions:
            level: level
            logger: logger_name
            message: message
            timestamp: "@timestamp"
            trace_id: traceId
            span_id: spanId
            thread: thread_name
            class: logger_name
      - labels:
          level:
          logger:
          trace_id:
          span_id:
          thread:
          class:
      - timestamp:
          format: "2006-01-02T15:04:05.000Z"
          source: timestamp
      - output:
          source: message

  # Scrape PostgreSQL logs
  - job_name: postgres
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["postgres-db"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
        replacement: "${1}"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "logstream"
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} \w+) \[(?P<pid>\d+)\] (?P<level>\w+):  (?P<message>.*)'
      - labels:
          level:
          pid:
      - timestamp:
          format: "2006-01-02 15:04:05.000 MST"
          source: timestamp
      - output:
          source: message

  # Scrape Prometheus logs
  - job_name: prometheus
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["prometheus"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
        replacement: "${1}"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "logstream"
    pipeline_stages:
      - regex:
          expression: '^level=(?P<level>\w+) ts=(?P<timestamp>[\d\-T:\.Z]+) caller=(?P<caller>[^\s]+) (?P<message>.*)'
      - labels:
          level:
          caller:
      - timestamp:
          format: "2006-01-02T15:04:05.000Z"
          source: timestamp
      - output:
          source: message

  # Scrape Grafana logs
  - job_name: grafana
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["grafana"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
        replacement: "${1}"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "logstream"
    pipeline_stages:
      - regex:
          expression: '^t=(?P<timestamp>[\d\-T:\.Z]+) lvl=(?P<level>\w+) msg="(?P<message>[^"]*)"'
      - labels:
          level:
      - timestamp:
          format: "2006-01-02T15:04:05Z"
          source: timestamp
      - output:
          source: message

  # Scrape Jaeger logs
  - job_name: jaeger
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["jaeger"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container_name"
        replacement: "${1}"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "logstream"
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: msg
            timestamp: ts
            logger: logger
      - labels:
          level:
          logger:
      - timestamp:
          format: "2006-01-02T15:04:05.000Z"
          source: timestamp
      - output:
          source: message
