groups:
  - name: mobile-banking-backend
    rules:
      # Application Health Alerts
      - alert: ApplicationDown
        expr: up{job="mobile-banking-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Mobile Banking Backend is down"
          description: "Mobile Banking Backend has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for the last 5 minutes."

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds."

      # JVM Alerts
      - alert: HighMemoryUsage
        expr: (jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"}) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High JVM memory usage"
          description: "JVM heap memory usage is {{ $value }}%."

      - alert: HighGCTime
        expr: rate(jvm_gc_pause_seconds_sum[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High garbage collection time"
          description: "GC time is {{ $value }} seconds per second."

  - name: database
    rules:
      # Database Health Alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres-exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute."

      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connection usage"
          description: "Database connection usage is {{ $value }}%."

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_database_tup_returned[5m]) / rate(pg_stat_database_tup_fetched[5m]) < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database slow queries detected"
          description: "Database query efficiency is low: {{ $value }}."

      - alert: DatabaseHighIOWait
        expr: rate(pg_stat_database_blk_read_time[5m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database I/O wait time"
          description: "Database I/O wait time is {{ $value }} ms."
